
CREATE TABLE DS_ACTIVE (
  PID NUMBER NOT NULL ,
  APP_CODE NVARCHAR2(64) ,
  OPENID NVARCHAR2(50) ,
  CREATE_TIME DATE ,
  PLAT NVARCHAR2(10) ,
  PHONE NVARCHAR2(20) ,
  INVITE_CODE NVARCHAR2(30) ,
  USED_CODE NVARCHAR2(30) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) 
)
/
COMMENT ON COLUMN DS_ACTIVE.PID IS '主键';
COMMENT ON COLUMN DS_ACTIVE.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_ACTIVE.OPENID IS 'OPENID';
COMMENT ON COLUMN DS_ACTIVE.CREATE_TIME IS '参加时间';
COMMENT ON COLUMN DS_ACTIVE.PLAT IS '预约平台';
COMMENT ON COLUMN DS_ACTIVE.PHONE IS '预约手机号';
COMMENT ON COLUMN DS_ACTIVE.INVITE_CODE IS '邀请码';
COMMENT ON COLUMN DS_ACTIVE.USED_CODE IS '使用的邀请码';
COMMENT ON COLUMN DS_ACTIVE.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_ACTIVE.VERSION_CODE IS '活动版本 ';
COMMENT ON TABLE DS_ACTIVE IS '活动参与表';

-- ----------------------------
-- Records of DS_ACTIVE
-- ----------------------------
INSERT INTO DS_ACTIVE VALUES ('1', NULL, NULL, TO_DATE('2019-07-02 16:23:49', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '158811463091', 'fsdfsfsdfs', '2sfsafetttttt', NULL, NULL);
INSERT INTO DS_ACTIVE VALUES ('595679446606807040', 'tl3d', NULL, TO_DATE('2019-07-02 18:17:27', 'SYYYY-MM-DD HH24:MI:SS'), 'Android', '15881146309', 'giftcode2', NULL, 'appointment', '20190701');
INSERT INTO DS_ACTIVE VALUES ('595686745266192384', 'tl3d', '15881146309', TO_DATE('2019-07-02 18:46:27', 'SYYYY-MM-DD HH24:MI:SS'), 'IOS', '158811463093', 'giftcode3', 'giftcode2', 'appointment', '20190701');


CREATE TABLE DS_ACTIVE_OFFSET (
  PID NUMBER NOT NULL ,
  NUM NUMBER ,
  TIME NUMBER ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) 
)
/
COMMENT ON COLUMN DS_ACTIVE_OFFSET.PID IS '主键';
COMMENT ON COLUMN DS_ACTIVE_OFFSET.NUM IS '偏移量';
COMMENT ON COLUMN DS_ACTIVE_OFFSET.TIME IS '更新时间 0-24，0实时';
COMMENT ON COLUMN DS_ACTIVE_OFFSET.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_ACTIVE_OFFSET.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_ACTIVE_OFFSET.VERSION_CODE IS '活动版本';
COMMENT ON TABLE DS_ACTIVE_OFFSET IS '预约偏移量';

CREATE TABLE DS_GIFT_CODE (
  CODE NVARCHAR2(30) NOT NULL ,
  STATUS NUMBER ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) 
)
/
COMMENT ON COLUMN DS_GIFT_CODE.CODE IS '邀请码';
COMMENT ON COLUMN DS_GIFT_CODE.STATUS IS '状态  0：未使用，1：已使用';
COMMENT ON COLUMN DS_GIFT_CODE.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_GIFT_CODE.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_GIFT_CODE.VERSION_CODE IS '活动版本';

-- ----------------------------
-- Records of DS_GIFT_CODE
-- ----------------------------
INSERT INTO DS_GIFT_CODE VALUES ('giftcode1', '1', '1', '1', '1');
INSERT INTO DS_GIFT_CODE VALUES ('giftcode2', '1', NULL, NULL, NULL);
INSERT INTO DS_GIFT_CODE VALUES ('giftcode3', '1', NULL, NULL, NULL);

CREATE TABLE DS_GIFT_ITEM (
  PID NUMBER NOT NULL ,
  TYPE NUMBER ,
  NAME NVARCHAR2(30) ,
  NUM NUMBER ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) ,
  ICON NVARCHAR2(255) 
)
/
COMMENT ON COLUMN DS_GIFT_ITEM.PID IS '主键';
COMMENT ON COLUMN DS_GIFT_ITEM.TYPE IS '奖品的档位';
COMMENT ON COLUMN DS_GIFT_ITEM.NAME IS '奖品名称';
COMMENT ON COLUMN DS_GIFT_ITEM.NUM IS '奖品数量';
COMMENT ON COLUMN DS_GIFT_ITEM.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_GIFT_ITEM.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_GIFT_ITEM.VERSION_CODE IS '活动版本';
COMMENT ON COLUMN DS_GIFT_ITEM.ICON IS '奖励ICON';
COMMENT ON TABLE DS_GIFT_ITEM IS '奖品表';

-- ----------------------------
-- Records of DS_GIFT_ITEM
-- ----------------------------
INSERT INTO DS_GIFT_ITEM VALUES ('1', '1', '3级穿透宝石', '1', '1', '1', '1', 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('2', '2', '3级穿透宝石', '2', '1', '1', '1', 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('3', '3', '3级穿透宝石', '3', '1', '1', '1', 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('4', '3', '3级穿透宝石', '1', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('5', '4', '3级穿透宝石', '4', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('6', '5', '3级穿透宝石', '5', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('7', '6', '3级穿透宝石', '1', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('8', '7', '3级穿透宝石', '1', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('9', '8', '3级穿透宝石', '1', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('10', '9', '3级穿透宝石', '1', NULL, NULL, NULL, 'inc/images/prize.png');
INSERT INTO DS_GIFT_ITEM VALUES ('11', '10', '3级穿透宝石', '1', NULL, NULL, NULL, 'inc/images/prize.png');

CREATE TABLE DS_GIFT_TYPE (
  PID NUMBER NOT NULL ,
  NAME NVARCHAR2(20) ,
  NUM NUMBER ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) ,
  SERVER NUMBER 
)
/
COMMENT ON COLUMN DS_GIFT_TYPE.PID IS '主键';
COMMENT ON COLUMN DS_GIFT_TYPE.NAME IS '奖励档位的名称';
COMMENT ON COLUMN DS_GIFT_TYPE.NUM IS '奖励达成人数';
COMMENT ON COLUMN DS_GIFT_TYPE.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_GIFT_TYPE.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_GIFT_TYPE.VERSION_CODE IS '活动版本';
COMMENT ON COLUMN DS_GIFT_TYPE.SERVER IS '服务器 1：老服，2：新服';
COMMENT ON TABLE DS_GIFT_TYPE IS '奖品档位表';

-- ----------------------------
-- Records of DS_GIFT_TYPE
-- ----------------------------
INSERT INTO DS_GIFT_TYPE VALUES ('1', '1万预约', '10000', '1', '1', '1', '1');
INSERT INTO DS_GIFT_TYPE VALUES ('2', '2万预约', '20000', '1', '1', '1', '1');
INSERT INTO DS_GIFT_TYPE VALUES ('3', '3万预约', '30000', '1', '1', '1', '1');
INSERT INTO DS_GIFT_TYPE VALUES ('4', '4万预约', '40000', '1', '1', '1', '1');
INSERT INTO DS_GIFT_TYPE VALUES ('5', '5万预约', '50000', '1', '1', '1', '1');
INSERT INTO DS_GIFT_TYPE VALUES ('6', '1万预约', '10000', NULL, NULL, NULL, '2');
INSERT INTO DS_GIFT_TYPE VALUES ('7', '2万预约', '20000', NULL, NULL, NULL, '2');
INSERT INTO DS_GIFT_TYPE VALUES ('8', '3万预约', '30000', NULL, NULL, NULL, '2');
INSERT INTO DS_GIFT_TYPE VALUES ('9', '4万预约', '40000', NULL, NULL, NULL, '2');
INSERT INTO DS_GIFT_TYPE VALUES ('10', '5万预约', '50000', NULL, NULL, NULL, '2');

CREATE TABLE DS_INVITE_GIFT (
  PID NUMBER NOT NULL ,
  NAME NVARCHAR2(255) ,
  NUM NUMBER ,
  CODE NVARCHAR2(30) ,
  ICON NVARCHAR2(255) ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) 
)
/
COMMENT ON COLUMN DS_INVITE_GIFT.PID IS '主键';
COMMENT ON COLUMN DS_INVITE_GIFT.NAME IS '奖励名称';
COMMENT ON COLUMN DS_INVITE_GIFT.NUM IS '奖励达成人数';
COMMENT ON COLUMN DS_INVITE_GIFT.CODE IS '邀请礼包码';
COMMENT ON COLUMN DS_INVITE_GIFT.ICON IS '奖励ICON';
COMMENT ON COLUMN DS_INVITE_GIFT.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_INVITE_GIFT.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_INVITE_GIFT.VERSION_CODE IS '活动版本';
COMMENT ON TABLE DS_INVITE_GIFT IS '邀请奖励列表';

-- ----------------------------
-- Records of DS_INVITE_GIFT
-- ----------------------------
INSERT INTO DS_INVITE_GIFT VALUES ('1', '3级穿透宝石', '3', '123', 'inc/images/prize.png', '1', '1', '1');
INSERT INTO DS_INVITE_GIFT VALUES ('3', '3级穿透宝石', '1', '111', 'inc/images/prize.png', NULL, NULL, NULL);
INSERT INTO DS_INVITE_GIFT VALUES ('2', '3级穿透宝石', '2', '321', 'inc/images/prize.png', NULL, NULL, NULL);

CREATE TABLE DS_INVITE_CONFIG (
  PID NUMBER NOT NULL ,
  START_TIME DATE ,
  END_TIME DATE ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) 
)
/
COMMENT ON COLUMN DS_INVITE_CONFIG.PID IS '主键';
COMMENT ON COLUMN DS_INVITE_CONFIG.START_TIME IS '开始时间';
COMMENT ON COLUMN DS_INVITE_CONFIG.END_TIME IS '结束时间';
COMMENT ON COLUMN DS_INVITE_CONFIG.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_INVITE_CONFIG.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_INVITE_CONFIG.VERSION_CODE IS '活动版本';
COMMENT ON TABLE DS_INVITE_CONFIG IS '邀请奖励配置信息';

-- ----------------------------
-- Records of DS_INVITE_CONFIG
-- ----------------------------
INSERT INTO DS_INVITE_CONFIG VALUES ('1', TO_DATE('2019-07-01 21:23:35', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2019-07-26 21:23:40', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL);

CREATE TABLE DS_INVITE_RECORD (
  PID NUMBER NOT NULL ,
  PHONE NVARCHAR2(20) ,
  CREATE_TIME DATE ,
  INVITE_GIFT_PID NUMBER ,
  APP_CODE NVARCHAR2(64) ,
  ACTIVITY_CODE NVARCHAR2(64) ,
  VERSION_CODE NVARCHAR2(64) ,
  PLAT NVARCHAR2(10) ,
  SERVER_NAME NVARCHAR2(64) ,
  ROLE_NAME NVARCHAR2(64) 
)
/
COMMENT ON COLUMN DS_INVITE_RECORD.PID IS '主键';
COMMENT ON COLUMN DS_INVITE_RECORD.PHONE IS '手机号';
COMMENT ON COLUMN DS_INVITE_RECORD.CREATE_TIME IS '领奖时间';
COMMENT ON COLUMN DS_INVITE_RECORD.INVITE_GIFT_PID IS '邀请奖励的pid';
COMMENT ON COLUMN DS_INVITE_RECORD.APP_CODE IS '应用代码';
COMMENT ON COLUMN DS_INVITE_RECORD.ACTIVITY_CODE IS '活动代码 ';
COMMENT ON COLUMN DS_INVITE_RECORD.VERSION_CODE IS '活动版本';
COMMENT ON COLUMN DS_INVITE_RECORD.PLAT IS '手机系统';
COMMENT ON COLUMN DS_INVITE_RECORD.SERVER_NAME IS '服务器名';
COMMENT ON COLUMN DS_INVITE_RECORD.ROLE_NAME IS '角色名';
COMMENT ON TABLE DS_INVITE_RECORD IS '邀请奖励领取记录表';

-- ----------------------------
-- Records of DS_INVITE_RECORD
-- ----------------------------
INSERT INTO DS_INVITE_RECORD VALUES ('596656942466727936', '15881146309', TO_DATE('2019-07-05 11:01:40', 'SYYYY-MM-DD HH24:MI:SS'), '3', 'tl3d', 'appointment', '20190701', 'Android', 'S003-只手遮天', '11111111-11111111');



-- ----------------------------
-- Primary Key structure for table DS_ACTIVE
-- ----------------------------
ALTER TABLE DS_ACTIVE ADD CONSTRAINT "SYS_C0011935" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_ACTIVE
-- ----------------------------
ALTER TABLE DS_ACTIVE ADD CONSTRAINT "SYS_C0011527" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_ACTIVE ADD CONSTRAINT "SYS_C0011934" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table DS_ACTIVE
-- ----------------------------
CREATE INDEX "IDX_PHONE"
  ON DS_ACTIVE ("PHONE" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "IDX_USED_CODE"
  ON DS_ACTIVE ("USED_CODE" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table DS_ACTIVE_OFFSET
-- ----------------------------
ALTER TABLE DS_ACTIVE_OFFSET ADD CONSTRAINT "SYS_C0011939" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_ACTIVE_OFFSET
-- ----------------------------
ALTER TABLE DS_ACTIVE_OFFSET ADD CONSTRAINT "SYS_C0011528" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_ACTIVE_OFFSET ADD CONSTRAINT "SYS_C0011938" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DS_GIFT_CODE
-- ----------------------------
ALTER TABLE DS_GIFT_CODE ADD CONSTRAINT "SYS_C0011953" PRIMARY KEY ("CODE");

-- ----------------------------
-- Checks structure for table DS_GIFT_CODE
-- ----------------------------
ALTER TABLE DS_GIFT_CODE ADD CONSTRAINT "SYS_C0011529" CHECK ("CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_GIFT_CODE ADD CONSTRAINT "SYS_C0011952" CHECK ("CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DS_GIFT_ITEM
-- ----------------------------
ALTER TABLE DS_GIFT_ITEM ADD CONSTRAINT "SYS_C0011933" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_GIFT_ITEM
-- ----------------------------
ALTER TABLE DS_GIFT_ITEM ADD CONSTRAINT "SYS_C0011530" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_GIFT_ITEM ADD CONSTRAINT "SYS_C0011932" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DS_GIFT_TYPE
-- ----------------------------
ALTER TABLE DS_GIFT_TYPE ADD CONSTRAINT "SYS_C0011911" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_GIFT_TYPE
-- ----------------------------
ALTER TABLE DS_GIFT_TYPE ADD CONSTRAINT "SYS_C0011531" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_GIFT_TYPE ADD CONSTRAINT "SYS_C0011910" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DS_INVITE_GIFT
-- ----------------------------
ALTER TABLE DS_INVITE_GIFT ADD CONSTRAINT "SYS_C0011937" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_INVITE_GIFT
-- ----------------------------
ALTER TABLE DS_INVITE_GIFT ADD CONSTRAINT "SYS_C0011532" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_INVITE_GIFT ADD CONSTRAINT "SYS_C0011936" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DS_INVITE_CONFIG
-- ----------------------------
ALTER TABLE DS_INVITE_CONFIG ADD CONSTRAINT "SYS_C0012374" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_INVITE_CONFIG
-- ----------------------------
ALTER TABLE DS_INVITE_CONFIG ADD CONSTRAINT "SYS_C0011943" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_INVITE_CONFIG ADD CONSTRAINT "SYS_C0012373" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DS_INVITE_RECORD
-- ----------------------------
ALTER TABLE DS_INVITE_RECORD ADD CONSTRAINT "SYS_C0012376" PRIMARY KEY (PID);

-- ----------------------------
-- Checks structure for table DS_INVITE_RECORD
-- ----------------------------
ALTER TABLE DS_INVITE_RECORD ADD CONSTRAINT "SYS_C0011945" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE DS_INVITE_RECORD ADD CONSTRAINT "SYS_C0012375" CHECK (PID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
