/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1 cyactivity
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 127.0.0.1:1521
 Source Schema         : CYACTIVITY

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 24/06/2019 00:25:28
*/


-- ----------------------------
-- Table structure for TB_CORE_ACTIVITY
-- ----------------------------
DROP TABLE "CYACTIVITY"."TB_CORE_ACTIVITY";
CREATE TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" (
  "ACTIVITY_CODE" NVARCHAR2(30) NOT NULL ,
  "APP_CODE" NVARCHAR2(30) NOT NULL ,
  "ACTIVITY_NAME" NVARCHAR2(30) NOT NULL ,
  "ACTIVITY_VERSION" NVARCHAR2(20) NOT NULL ,
  "START_TIME" DATE ,
  "END_TIME" DATE ,
  "OPEN_WX" NUMBER(1) NOT NULL ,
  "WX_ID" NVARCHAR2(100) ,
  "SUPPORT_PLAT" NUMBER(10) NOT NULL ,
  "STATUS" NUMBER(1) ,
  "MOBILE_URL" NVARCHAR2(255) ,
  "LANDING_URL" NVARCHAR2(255) ,
  "WECHAT_URL" NVARCHAR2(255) ,
  "DESCRIPTION" NVARCHAR2(255) ,
  "UPDATE_TIME" DATE ,
  "CREATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."ACTIVITY_CODE" IS '活动代码 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."APP_CODE" IS '应用代码 旧活动的game';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."ACTIVITY_NAME" IS '活动名称 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."ACTIVITY_VERSION" IS '活动版本 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."START_TIME" IS '开始时间 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."END_TIME" IS '结束时间 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."OPEN_WX" IS '微信授权模式 是否开启微信 0 不开启 1 开启基础登陆 2 开启信息授权';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."WX_ID" IS '使用微信APP_ID ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."SUPPORT_PLAT" IS '支持的账号类型 所有支持的类型数值总和。WECHAT(1，CHANGYOU(2，CYOU(4，CHANGYOUJIA(8，DJ(16';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."STATUS" IS '状态 0停用，1启用';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."MOBILE_URL" IS '手机入口地址 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."LANDING_URL" IS 'PC入口地址 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."WECHAT_URL" IS '微信入口地址 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."DESCRIPTION" IS '活动描述 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."UPDATE_TIME" IS '更新时间 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_ACTIVITY"."CREATE_TIME" IS '创建时间 ';
COMMENT ON TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" IS '活动信息 主要记录活动标识、key、是否有效、开始结束时间等';

-- ----------------------------
-- Table structure for TB_CORE_APP
-- ----------------------------
DROP TABLE "CYACTIVITY"."TB_CORE_APP";
CREATE TABLE "CYACTIVITY"."TB_CORE_APP" (
  "APP_CODE" NVARCHAR2(30) NOT NULL ,
  "APP_NAME" NVARCHAR2(30) NOT NULL ,
  "APP_KEY" NVARCHAR2(30) ,
  "STATUS" NUMBER DEFAULT 1 ,
  "CREATE_TIME" DATE ,
  "UPDATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_APP"."APP_CODE" IS '代码主键 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_APP"."APP_NAME" IS '名称 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_APP"."APP_KEY" IS '应用KEY ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_APP"."STATUS" IS '状态 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_APP"."CREATE_TIME" IS 'CREATE_TIME ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_APP"."UPDATE_TIME" IS 'UPDATE_TIME ';
COMMENT ON TABLE "CYACTIVITY"."TB_CORE_APP" IS '应用（游戏）表 一个游戏作为一个应用';

-- ----------------------------
-- Table structure for TB_CORE_USER_OPEN
-- ----------------------------
DROP TABLE "CYACTIVITY"."TB_CORE_USER_OPEN";
CREATE TABLE "CYACTIVITY"."TB_CORE_USER_OPEN" (
  "GUID" NVARCHAR2(60) NOT NULL ,
  "OPENID" NVARCHAR2(100) NOT NULL ,
  "OPEN_TYPE" NUMBER(5) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_USER_OPEN"."GUID" IS 'GUID ';
COMMENT ON COLUMN "CYACTIVITY"."TB_CORE_USER_OPEN"."OPENID" IS 'OPENID ';
COMMENT ON TABLE "CYACTIVITY"."TB_CORE_USER_OPEN" IS 'TOKEN用户与其他用户表关系 ';

-- ----------------------------
-- Table structure for TB_WX_APP
-- ----------------------------
DROP TABLE "CYACTIVITY"."TB_WX_APP";
CREATE TABLE "CYACTIVITY"."TB_WX_APP" (
  "APP_ID" NVARCHAR2(100) NOT NULL ,
  "APP_NAME" NVARCHAR2(30) NOT NULL ,
  "SECRET" NVARCHAR2(200) NOT NULL ,
  "TOKEN" NVARCHAR2(255) ,
  "STATUS" NUMBER(1) DEFAULT 1 ,
  "CREATE_TIME" DATE ,
  "UPDATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."APP_ID" IS '标识 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."APP_NAME" IS '名称 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."SECRET" IS '安全密钥 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."TOKEN" IS 'TOKEN 统一刷新token';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."STATUS" IS 'STATUS ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."CREATE_TIME" IS 'CREATE_TIME ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_APP"."UPDATE_TIME" IS 'UPDATE_TIME ';
COMMENT ON TABLE "CYACTIVITY"."TB_WX_APP" IS '微信设置表 ';

-- ----------------------------
-- Table structure for TB_WX_USER
-- ----------------------------
DROP TABLE "CYACTIVITY"."TB_WX_USER";
CREATE TABLE "CYACTIVITY"."TB_WX_USER" (
  "OPENID" NVARCHAR2(50) NOT NULL ,
  "WX_ID" NVARCHAR2(100) NOT NULL ,
  "UNIONID" NVARCHAR2(50) ,
  "NICKNAME" NVARCHAR2(200) ,
  "SEX" NUMBER(1) DEFAULT 0 ,
  "CITY" NVARCHAR2(100) ,
  "PROVINCE" NVARCHAR2(100) ,
  "COUNTRY" NVARCHAR2(100) ,
  "LANGUAGE" NVARCHAR2(20) ,
  "HEADIMGURL" NVARCHAR2(255) ,
  "PRIVILEGE" NCLOB ,
  "STATUS" NUMBER(1) DEFAULT 0 ,
  "LAST_SUBSCRIBE_TIME" DATE ,
  "FIRST_SUBSCRIBE_TIME" DATE ,
  "PRE_OPENID" NVARCHAR2(50) ,
  "CREATE_TIME" DATE ,
  "UPDATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."OPENID" IS 'OPENID ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."WX_ID" IS '微信APP_ID ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."UNIONID" IS 'UNIONID ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."NICKNAME" IS '昵称 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."SEX" IS '性别 0:未知，1:男，2:女';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."CITY" IS '所在城市 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."PROVINCE" IS '所在省份 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."COUNTRY" IS '所在国家 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."LANGUAGE" IS '语言 简体中文是zh_CN';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."HEADIMGURL" IS '头像 最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."PRIVILEGE" IS '用户特权 用户特权信息，json 数组，如微信沃卡用户为（chinaunicom）';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."STATUS" IS '关注状态 0未关注，1已关注，2取消关注';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."LAST_SUBSCRIBE_TIME" IS '最后一次关注时间 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."FIRST_SUBSCRIBE_TIME" IS '第一次关注时间 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."PRE_OPENID" IS '邀请用户 ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."CREATE_TIME" IS 'CREATE_TIME ';
COMMENT ON COLUMN "CYACTIVITY"."TB_WX_USER"."UPDATE_TIME" IS 'UPDATE_TIME ';
COMMENT ON TABLE "CYACTIVITY"."TB_WX_USER" IS '微信用户表 ';

-- ----------------------------
-- Table structure for T_ACTIVE
-- ----------------------------
DROP TABLE "CYACTIVITY"."T_ACTIVE";
CREATE TABLE "CYACTIVITY"."T_ACTIVE" (
  "PID" NUMBER NOT NULL ,
  "APP_CODE" NVARCHAR2(30) ,
  "OPENID" NVARCHAR2(50) ,
  "CREATE_TIME" DATE ,
  "PLAT" NVARCHAR2(10) ,
  "PHONE" NVARCHAR2(20) ,
  "INVITE_CODE" NVARCHAR2(30) ,
  "USED_CODE" NVARCHAR2(30) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."PID" IS '主键';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."APP_CODE" IS '应用代码 旧活动的game';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."OPENID" IS 'OPENID';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."CREATE_TIME" IS '参加时间';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."PLAT" IS '预约平台';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."PHONE" IS '预约手机号';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."INVITE_CODE" IS '邀请码';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE"."USED_CODE" IS '使用的邀请码';
COMMENT ON TABLE "CYACTIVITY"."T_ACTIVE" IS '活动参与表';

-- ----------------------------
-- Table structure for T_ACTIVE_OFFSET
-- ----------------------------
DROP TABLE "CYACTIVITY"."T_ACTIVE_OFFSET";
CREATE TABLE "CYACTIVITY"."T_ACTIVE_OFFSET" (
  "PID" NUMBER NOT NULL ,
  "NUM" NUMBER ,
  "TIME" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE_OFFSET"."PID" IS '主键';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE_OFFSET"."NUM" IS '偏移量';
COMMENT ON COLUMN "CYACTIVITY"."T_ACTIVE_OFFSET"."TIME" IS '更新时间 0-24，0实时';
COMMENT ON TABLE "CYACTIVITY"."T_ACTIVE_OFFSET" IS '预约偏移量';

-- ----------------------------
-- Table structure for T_GIFT_CODE
-- ----------------------------
DROP TABLE "CYACTIVITY"."T_GIFT_CODE";
CREATE TABLE "CYACTIVITY"."T_GIFT_CODE" (
  "CODE" NVARCHAR2(30) NOT NULL ,
  "STATUS" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_CODE"."CODE" IS '邀请码';
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_CODE"."STATUS" IS '状态  0：未使用，1：已使用';

-- ----------------------------
-- Table structure for T_GIFT_ITEM
-- ----------------------------
DROP TABLE "CYACTIVITY"."T_GIFT_ITEM";
CREATE TABLE "CYACTIVITY"."T_GIFT_ITEM" (
  "PID" NUMBER NOT NULL ,
  "TYPE" NUMBER ,
  "NAME" NVARCHAR2(30) ,
  "NUM" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_ITEM"."PID" IS '主键';
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_ITEM"."TYPE" IS '奖品的档位';
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_ITEM"."NAME" IS '奖品名称';
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_ITEM"."NUM" IS '奖品数量';
COMMENT ON TABLE "CYACTIVITY"."T_GIFT_ITEM" IS '奖品表';

-- ----------------------------
-- Table structure for T_GIFT_TYPE
-- ----------------------------
DROP TABLE "CYACTIVITY"."T_GIFT_TYPE";
CREATE TABLE "CYACTIVITY"."T_GIFT_TYPE" (
  "PID" NUMBER NOT NULL ,
  "NAME" NVARCHAR2(20) ,
  "NUM" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_TYPE"."PID" IS '主键';
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_TYPE"."NAME" IS '奖励档位的名称';
COMMENT ON COLUMN "CYACTIVITY"."T_GIFT_TYPE"."NUM" IS '奖励达成人数';
COMMENT ON TABLE "CYACTIVITY"."T_GIFT_TYPE" IS '奖品档位表';

-- ----------------------------
-- Table structure for T_INVITE_GIFT
-- ----------------------------
DROP TABLE "CYACTIVITY"."T_INVITE_GIFT";
CREATE TABLE "CYACTIVITY"."T_INVITE_GIFT" (
  "PID" NUMBER NOT NULL ,
  "NAME" NVARCHAR2(255) ,
  "NUM" NUMBER ,
  "CODE" NVARCHAR2(30) ,
  "ICON" NVARCHAR2(255) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CYACTIVITY"."T_INVITE_GIFT"."PID" IS '主键';
COMMENT ON COLUMN "CYACTIVITY"."T_INVITE_GIFT"."NAME" IS '奖励名称';
COMMENT ON COLUMN "CYACTIVITY"."T_INVITE_GIFT"."NUM" IS '奖励达成人数';
COMMENT ON COLUMN "CYACTIVITY"."T_INVITE_GIFT"."CODE" IS '邀请礼包码';
COMMENT ON COLUMN "CYACTIVITY"."T_INVITE_GIFT"."ICON" IS '奖励ICON';
COMMENT ON TABLE "CYACTIVITY"."T_INVITE_GIFT" IS '邀请奖励列表';

-- ----------------------------
-- Primary Key structure for table TB_CORE_ACTIVITY
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "PK_TB_CORE_ACTIVITY" PRIMARY KEY ("ACTIVITY_CODE", "APP_CODE", "ACTIVITY_VERSION");

-- ----------------------------
-- Checks structure for table TB_CORE_ACTIVITY
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "SYS_C0011785" CHECK ("ACTIVITY_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "SYS_C0011786" CHECK ("APP_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "SYS_C0011787" CHECK ("ACTIVITY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "SYS_C0011788" CHECK ("ACTIVITY_VERSION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "SYS_C0011789" CHECK ("OPEN_WX" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_ACTIVITY" ADD CONSTRAINT "SYS_C0011790" CHECK ("SUPPORT_PLAT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TB_CORE_APP
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_CORE_APP" ADD CONSTRAINT "PK_TB_CORE_APP" PRIMARY KEY ("APP_CODE");

-- ----------------------------
-- Checks structure for table TB_CORE_APP
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_CORE_APP" ADD CONSTRAINT "SYS_C0011792" CHECK ("APP_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_APP" ADD CONSTRAINT "SYS_C0011793" CHECK ("APP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TB_CORE_USER_OPEN
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_CORE_USER_OPEN" ADD CONSTRAINT "PK_TB_CORE_USER_OPEN" PRIMARY KEY ("GUID", "OPENID");

-- ----------------------------
-- Checks structure for table TB_CORE_USER_OPEN
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_CORE_USER_OPEN" ADD CONSTRAINT "SYS_C0011795" CHECK ("GUID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_CORE_USER_OPEN" ADD CONSTRAINT "SYS_C0011796" CHECK ("OPENID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TB_WX_APP
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_WX_APP" ADD CONSTRAINT "PK_TB_WX_APP" PRIMARY KEY ("APP_ID");

-- ----------------------------
-- Checks structure for table TB_WX_APP
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_WX_APP" ADD CONSTRAINT "SYS_C0011798" CHECK ("APP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_WX_APP" ADD CONSTRAINT "SYS_C0011799" CHECK ("APP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_WX_APP" ADD CONSTRAINT "SYS_C0011800" CHECK ("SECRET" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TB_WX_USER
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_WX_USER" ADD CONSTRAINT "PK_TB_WX_USER" PRIMARY KEY ("OPENID");

-- ----------------------------
-- Checks structure for table TB_WX_USER
-- ----------------------------
ALTER TABLE "CYACTIVITY"."TB_WX_USER" ADD CONSTRAINT "SYS_C0011802" CHECK ("OPENID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CYACTIVITY"."TB_WX_USER" ADD CONSTRAINT "SYS_C0011803" CHECK ("WX_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_ACTIVE
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_ACTIVE" ADD CONSTRAINT "SYS_C0011935" PRIMARY KEY ("PID");

-- ----------------------------
-- Checks structure for table T_ACTIVE
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_ACTIVE" ADD CONSTRAINT "SYS_C0011934" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table T_ACTIVE
-- ----------------------------
CREATE INDEX "CYACTIVITY"."IDX_PHONE"
  ON "CYACTIVITY"."T_ACTIVE" ("PHONE" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "CYACTIVITY"."IDX_USED_CODE"
  ON "CYACTIVITY"."T_ACTIVE" ("USED_CODE" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table T_ACTIVE_OFFSET
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_ACTIVE_OFFSET" ADD CONSTRAINT "SYS_C0011939" PRIMARY KEY ("PID");

-- ----------------------------
-- Checks structure for table T_ACTIVE_OFFSET
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_ACTIVE_OFFSET" ADD CONSTRAINT "SYS_C0011938" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_GIFT_CODE
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_GIFT_CODE" ADD CONSTRAINT "SYS_C0011953" PRIMARY KEY ("CODE");

-- ----------------------------
-- Checks structure for table T_GIFT_CODE
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_GIFT_CODE" ADD CONSTRAINT "SYS_C0011952" CHECK ("CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_GIFT_ITEM
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_GIFT_ITEM" ADD CONSTRAINT "SYS_C0011933" PRIMARY KEY ("PID");

-- ----------------------------
-- Checks structure for table T_GIFT_ITEM
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_GIFT_ITEM" ADD CONSTRAINT "SYS_C0011932" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_GIFT_TYPE
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_GIFT_TYPE" ADD CONSTRAINT "SYS_C0011911" PRIMARY KEY ("PID");

-- ----------------------------
-- Checks structure for table T_GIFT_TYPE
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_GIFT_TYPE" ADD CONSTRAINT "SYS_C0011910" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_INVITE_GIFT
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_INVITE_GIFT" ADD CONSTRAINT "SYS_C0011937" PRIMARY KEY ("PID");

-- ----------------------------
-- Checks structure for table T_INVITE_GIFT
-- ----------------------------
ALTER TABLE "CYACTIVITY"."T_INVITE_GIFT" ADD CONSTRAINT "SYS_C0011936" CHECK ("PID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
